version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: hawkapp
    ports:
      - "8080:8080"
    networks:
      - hawk-network

networks:
  hawk-network:
